swagger: "2.0"
info:
  version: 1.0.0
  title: Sociopool Task
  description: Public API
  contact:
    email: temp@gmail.com
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: localhost:8349

basePath: /
schemes:
#  - https
- http
tags:
- name: chat
  description: all functions related chat accounts

paths:
  /user:
    post:
      tags:
      - "user"
      summary: add new chat
      operationId: addchat
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        required: true
        schema:
          type: object
          properties:
            intent_matched:
              type: string
            psid:
              type: string
            sender:
              type: string
              # format: date-time
            sessionId:
              type: string
      responses:
        "200":
          description: successful operation
          schema:
            $ref: "#/definitions/ApiResponse"
    
  /chatLogs:
    post:
      tags:
      - "user"
      summary: Get chat details
      operationId: getChat
      consumes:
      - application/json

      produces:
      - application/json
      parameters:
      # - in: path
      #   name: id
      #   description: id  of the user
      #   required: true
      #   type: string
      - in: body
        name: filters
        schema:
          type: object
          properties:
            startDate:
              type: string
              format: date-time
            endDate:
              type: string
              format: date-time
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ApiResponse'
   
  
securityDefinitions:
  bearerAuth:
    type: apiKey
    name: Authorization
    in: header
definitions:
  ApiResponse:
    type: object
    properties:
      type:
        type: string
      success:
        type: boolean
      error:
        type: boolean
      message:
        type: string
      data:
        type: object

